name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check that 'go mod tidy' is clean
        run: go mod tidy --diff || (echo "Please run 'go mod tidy'." && exit 1)

      - uses: golangci/golangci-lint-action@v9
        with:
          only-new-issues: true
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: lint
    env:
      CGO_ENABLED: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: |
            go.sum
            Makefile

      - uses: actions/cache@v5
        with:
          path: ~/.ollama
          key: ${{ runner.os }}-ollama

      - name: Setup Ollama
        uses: ai-action/setup-ollama@v2

      - name: Pull tinyllama
        run: ollama pull tinyllama:1.1b

      - name: go test
        if: always()
        run: go test -count=1 ./
